/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aptl_jnidemo_NativeSorting */

#ifndef _Included_com_aptl_jnidemo_NativeSorting
#define _Included_com_aptl_jnidemo_NativeSorting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aptl_jnidemo_NativeSorting
 * Method:    nativeSort
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_aptl_jnidemo_NativeSorting_nativeSort
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_aptl_jnidemo_NativeSorting
 * Method:    nativeSortWithCallback
 * Signature: ([ILcom/aptl/jnidemo/NativeSorting/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_aptl_jnidemo_NativeSorting_nativeSortWithCallback
  (JNIEnv *, jobject, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
